spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    hidden-method:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.default_batch_fetch_size: 500
  datasource:
    url: jdbc:mysql://localhost:3306/traffic?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    remote:
      restart:
        enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
